### ISSUE TITLE
Need someone to write some docs?

### ISSUE THREAD

**Issue by symgryph** [henry40408/mono-rs#32]
I did manage to get your program working on aarch64 (specifically cdu) but really have no idea how to use it. I kind of figured out how to get the thing to run as daemon, but no idea on how to format my records file. I would be happy to document and submit PR since the help file really doesn't show me what the records are supposed to be like, and how to ipv6 records, which are the ones I am really interested in).

Thomas

**Comment by henry40408** [comment]
hi @symgryph sorry for late reply

> but no idea on how to format my records file

cdu accepts Cloudflare records as arguments. Can you describe how you use "records file"?

> help file really doesn't show me what the records are supposed to be like

```
$ cdu -h
...
    -r, --records <records>                Cloudflare records separated with comma e.g. a.x.com,b.x.com [env:
                                           CLOUDFLARE_RECORDS=]
...
```

Doesn't this help message clear enough for you? If doesn't, please help me to improve e.g. clear help message or document

> how to ipv6 records

My network environment does not support IPv6 at all :cry: but if you submit pull request, I will try my best to test it

**Comment by henry40408** [comment]
please re-open this issue if you're still interested in writing documentation
